name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.6'

      - name: Build with Go
        env:
          CGO_ENABLED: 0
        run: |
          platforms=(
            "linux amd64 simpledns_linux_amd64"
            "linux arm64 simpledns_linux_arm64"
            "windows amd64 simpledns_windows_amd64"
            "windows arm64 simpledns_windows_arm64"
          )
        
          for platform in "${platforms[@]}"; do
            set -- $platform
            GOOS=$1 GOARCH=$2 go build -o $3 -ldflags="-w -s" -trimpath -v .
          done

      - name: Extract changelog
        env:
          REF: ${{ github.ref }}
        run: |
          sed -n "/^## ${REF:10}/,/^## /{/^## /b;p}" CHANGELOG.md > RELEASE_CHANGELOG

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          body_path: RELEASE_CHANGELOG
          files: simpledns_*
